version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # port exposed : mysql port running inside container
      - "3306:3306"
    volumes:
        - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/FREEBIES_APP
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
    app-network: